### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by borijang** [Mukulthakur17/Skin-Pigment-Analysis#1]
Hi there,

Is there any chance of getting the dataset you used for this project?

Thanks!

**Comment by Mukulthakur17** [comment]
Hi @borijang, you can use https://github.com/Mukulthakur17/Skin-Pigment-Analysis/blob/master/Scraper.py to get the required dataset. You can also visit http://www.dermnet.com/images/ for more details.

**Comment by borijang** [comment]
Ah yes, I am aware of this dataset, I thought you had something extra :). 

Thanks a lot anyway, @Mukulthakur17!
